
// ES6 CLASS
// PUBLIC CHAT ROOM CLASS
class ROOM {
    constructor (id, name, creatorID, password) {
        this.id = id; // room ID -> generated by shortid in server
        this.name = name; // client set in front-end -> server receives data from front-end
        this.creator = creatorID; // client's unique ID/token
        this.client = [creatorID]; // array of clients ID that are in this room
        this.quantity = 1; // number of clients in this room
        this.password = password;
    }
    //
    addClient (clientID) {
        this.client.push(clientID);
        this.quantity ++;
    }

    removeClient (clientID) {
        let clientIndex = -1;
        for (let i = 0; i < this.client.length; i++) {
            if (this.client[i] === clientID) {
                clientIndex = i;
                break;
            }
        }
        this.client.splice(clientIndex, 1);
        this.quantity --;
    }

    changeName (newRoomName) {
        this.name = newRoomName;
    }
}

module.exports = ROOM; 